language: android
sudo: required
jdk: oraclejdk7
env:
  global:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
  - secure: Y0xQEf2626cxKjbqLf114ehRypcDxyEWCRgRLbyJ64OB+hfwCPRjerJw4FA8rBJqc9uJ5s76TqK3M9Txr4alwsP6ZJc6WC3rY5Ml9ZgxDLtjljjmSpqZScCIqCwWCz3kb1QyV2xj/YHF8T+PfCEA8iEuyBNCJNQqAU4ehRhmsOerzZBnvAE4avytHIV0AWam6B04JjPKVRtAJo1jYEfoLB54lWmb/ZwKCB44VhFuOVrK+Z+/dgg8T7+IYZTLMTdD79HfE9F4+Q9jL74dpHQ0Vyo3scd2jI5JnHQDDoXS9zLUAeuM6H/BRREtwl64+fo4bVstEXrJwGDpodcZ7MYhlEROy+mhSlFpBM9PSE6t2eO2r+bkEpo1OIU1Eg/yZpP9spo0kW6hv6WSxYuU9WHz/XiQ2FOqKsW9RDrszIKLEgoGAa9UF8JQHF78b+aEvCGsIC/j1YsfNj4/YArpoA4GZLArZ8G0exeBqDEz4iZUMOeOzNnDPWpSzS31484/JeKvGLIHRzTzZOJ3Z0nARMYdpelzgGunZ/AmGS20LiVhx4YQcJfpQn8fruvGUDM3v6Gvb8i81QUe9Lg/FEAB+2ODiPa1BJpYka57l0Jfa+LsWP2u1hmvlAi38j1FCmy4tMysOKYF5/xbIJg+e1hLi+eJbdG8aRo0RFKwQTWANcbvPjA=
  - secure: H3OKJIuZrshnve+QZ9xmjqOcwYhe4a+JoETMGa7xzRsWy9xxjmsVuWfvrnKFmJRBEsqj9zZMCRWTWMjaLlIcvew8Db93cwSzYUp95g3yOhcTE3rsKDNn2oyn7oHVuZ4+sv8k1kxYJexHTzMYLmXN/J7vbCcw221oWfirUUMe6S4YDW/C0KMv4omSttRp5pKe/ShgNVSKEby08jA7CPCqS3OhkW5Zp4vvpGw7zQEjXrWUrWiS0LjHBLvuAB/MPY6ez2KhEaiuNuHpCCR/aDWBMlAjYyGWEIjXGqRBqpQthfmxRQ66KlqUfryGQ8ZOvWnCFrKiG+3t4qRoEkVNiU/NMD/t1AsiVaEFVsVYF7Q+tYa7dlZ6zvtP/NeZPmcbbZLPe6YCM/u668i9d3szCFlFYJNpkvHLi0SK+0ETTl4zu9Ji9BHfEdGCIO/npvGNdj9g6lgTp04gZaDGRPQuFtcwjtFFtZIWHTI2iignSej62fyam+Vv6E8V1s6JzeDBO/J1f0VcCQaA4ID2fjqZ4qqceilkGE9gekw26AZErXQkqU/6AVpQOTQ3JPZ60OAIzGbCxdpOM8JJ/z2uoddNOEgf4WfgbSpY1UCNpQr8+Tsmy5g0sDavz8TWkSLGggDHj+aWCvMj/R2EaFoVZa0IVXA8fHjfVoD0GZDW1i9zFSV6Acs=
  - secure: ovQFeamkIX1eQkSAxwXX4dlBSRKx7ZP6UbOfR7TCuh3j957jVGmdD9pMVyy26eSRx0G6BX7w/j4vHSxID2cqfwo7AvNnu02bufHjhmUdp9zHYFQLYDr3Ymi72oRWOljofkh4GiUgJOCe4dUjawEXZWHYDlZKF/cP5IipA1PdwAqp3hGEY2+aqv6Xe2ii5pDEAJ22kI8OFR/rz7C1BkM3FHkvORh3DpdXA5nDdsC5mlDAzc6tDDzvNH5ijyIE32LONh7111vTupH96FCNEF69iPfYdArcHWODxQRguZFpnl6pIxayNmMyt5L109PZ13ogOw9Di5hubaJUN4+USyl0I7w/n66xQhfnCnbCmEjecGm63jgwJuQbClRFeUZ8Dp5bt9NIjBqoJFxs1pVfI9rWdB6W4fYwl/wUVN9fawcn3d/EisRyVnut+a12ZDtbUEeDEBOWQlDIKlTGa2SgO6gDszC30sjjVfkkxWoStKgnQz7M3ADjYToJ+igLojVXHQX+IYzPzzVbZ6FjBYUsTOGre9gzDnGfRXW8iDJL2GN622NcOtXGwDj+Cv4bdzB95P6vQ/K3wpYJEzMsivlMJAs4jzDFP9MKkgI7BELwNlJIjvFoJgY6QA96g0ouVQ7UG7lCe3gD7G4CCUimJItPDUECEqBfS+JLiGXiG7XYnUoffL8=
  - secure: lNdRNikpuX9W6L9PmM0GfUYIzdggDUXpcOnbTlKn8Ed7Z/GuvF1rL/6RNAnjysobSYRx3CrLJivxgMqEsi32AcLOQMPPfl3bG29KenARaQD/2hxKzV8Xv/73FYd1oswZj31WUAGeRtATmjZEqYsKM39rqfDU9yHylYwRJDqd5W1IXxUR7Qyny+NpCFIpcZr+2yCHz92EGEo5YsnIXQnSXxhlJlwUAhw+Sni40dzdhZBSPAv1PkWEDHKRWuSsyvMZRygLj+Qi0sHkWjNWmdR7LKr1DZMmPz3h8DV5UJFntOV07fT6mEcakanPfny2X2por5oJHwRjKJEWMu4wPniy56nntMklVZlx7GmPMdy/bef2SB3VUkcMJalGkSTuyZNId67X8FUHrfSZXlkMfw4ekavoFHTJ3/FC4R6CEwgTTfBZrlwZIlgmvtr3l1ZMheAFPp0Y3E2zv5lSj6BjYlK+JBDQTgG9mU0OXGhGEPwAUMe7y604dRzxqJ/VXM3nVcvBkz/C8YQ8mfJBZgSHPRbVB4hrAE12faUVv7CTpDmNct+VOS0zyvDLd7JzsOYVull9cEODWvOQqpll8T8Epsju0MbIFnxHeD7aJHabPPHZnrDUlyEe+NnmtkTHnGN6HCu9Fs9S/Hsaif7NTN1IXqnzgd2SbwRRVOyTPe3d4Fmmq7E=
  matrix:
  - ADB_INSTALL_TIMEOUT=15 ANDROID_BUILD_TOOLS_VERSION=23.0.2 ANDROID_TARGET=android-22
    ANDROID_ABI=armeabi-v7a
cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/android/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/android/gradle/wrapper/dists/"
  - "$HOME/android/.gradle/caches/"
  - "$HOME/android/.gradle/wrapper/"
android:
  components:
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - "$ANDROID_TARGET"
  - android-23
  - extra-google-google_play_services
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-$ANDROID_TARGET
script: "./gradlew build"
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y python2.7
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: VUz/DjL6esI3C5Wj3+/iuwTAsElk92vVU2QSjs+qWv80di6qGi1me7AGy6+PybX+Q5BB0qMOrGNX0X78AzDjozAcCoevfWKpxWgSw9hiz43uk6vLS7CUUB5HPmRXU3niSSDEZapqM9AYjgZctwCrk1q8yJMemsXuGHidRDYhpOdv7ytwtaDu3K8/TNTuMu4UdPoATDZ7AuM6NjuLbf5SXnLO3QFL+HwzVH/oe07A35xB8rKS4t2DjOPe5b/RLsytLnjo6dMDZRYl08bZ0J+kZLDKLZAI76WALmDR0Ruc6uGFtqK3DLi3YYC4Lu9CRj8lQ7NuaznMhgjzSzsJNOGeR1V7VoBIvzGIRk/AgExPXP0Jw/62wHpyUgznC1tS3ObPVAUwz5PLbOI8m+MG2JpIZampmA4Rog1mCXHI/pPYSmGd4zUmNO6WmNrzKVMSP51nBCjNPx7jvRBZkcAnKoTyOZPb5wCLP3Ac6hqChG6TQiLml8F8jKg8lqdnXJEs8nw2x/92F089R3s6MLwCUiAzhcUleRKUrISBGBRa93GAfwGXSSkXrpLYfsPwNNaWsybXvoIGHEvDLoRqFN5fPJhqWXYLLST5mQbiQxBANHQxOspxgKLiKEHv5WHPwwkSFG0e1Jeq5Q4MVS0/Rjne0qgvCgpx0YKUZe7XErC9LMHSO/o=
  file:
    - "app/build/outputs/apk/app-fdroid-debug.apk"
    - "app/build/outputs/apk/app-googleplay-debug.apk"
  on:
    tags: true
    repo: mananwason/apk-generator